### ISSUE TITLE
Temporary files shouldn't be checked in to a repository

### ISSUE THREAD

**Issue by yungyuc** [alishsuper/NSD_term_project#1]
I think [`.gitignore`](https://git-scm.com/docs/gitignore) may be used to avoid checking in temporary files like https://github.com/alishsuper/NSD_term_project/tree/master/.ipynb_checkpoints .

**Comment by yungyuc** [comment]
https://github.com/alishsuper/NSD_term_project/tree/master/python/__pycache__ can probably also get an entry in `.gitignore`.

**Comment by alishsuper** [comment]
@yungyuc I got it. Thanks!
